[build]
  command   = "rm -rf .next .netlify && node src/netifly-environment.js && npm run build"
  publish   = ".next"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[redirects]]
  from = "https://bashaliases.strubloid.com/*"
  to = "https://github.com/strubloid/.bash_aliases"
  status = 301
  force = true

[[redirects]]
  from = "https://spermwhale.strubloid.com/*"
  to = "https://github.com/strubloid/spermwhale"
  status = 301
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"